<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityEmployeeProxy extends \Entity\Employee implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setRoleId(\Entity\Role $role_id = NULL)
    {
        $this->_load();
        return parent::setRoleId($role_id);
    }

    public function getRoleId()
    {
        $this->_load();
        return parent::getRoleId();
    }

    public function setAreaId(\Entity\Area $area_id = NULL)
    {
        $this->_load();
        return parent::setAreaId($area_id);
    }

    public function getAreaId()
    {
        $this->_load();
        return parent::getAreaId();
    }

    public function setApartmentId(\Entity\Apartment $apt_id = NULL)
    {
        $this->_load();
        return parent::setApartmentId($apt_id);
    }

    public function getApartmentId()
    {
        $this->_load();
        return parent::getApartmentId();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setEmail($email)
    {
        $this->_load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->_load();
        return parent::getEmail();
    }

    public function setMobile($mobile)
    {
        $this->_load();
        return parent::setMobile($mobile);
    }

    public function getMobile()
    {
        $this->_load();
        return parent::getMobile();
    }

    public function setPassword($password)
    {
        $this->_load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->_load();
        return parent::getPassword();
    }

    public function setStatus($status)
    {
        $this->_load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->_load();
        return parent::getStatus();
    }

    public function setLoginTime($loginTime)
    {
        $this->_load();
        return parent::setLoginTime($loginTime);
    }

    public function getLoginTime()
    {
        $this->_load();
        return parent::getLoginTime();
    }

    public function setLogoutTime($logoutTime)
    {
        $this->_load();
        return parent::setLogoutTime($logoutTime);
    }

    public function getLogoutTime()
    {
        $this->_load();
        return parent::getLogoutTime();
    }

    public function setStoreIp($storeIp)
    {
        $this->_load();
        return parent::setStoreIp($storeIp);
    }

    public function getStoreIp()
    {
        $this->_load();
        return parent::getStoreIp();
    }

    public function setUpdatedAt($updated_at)
    {
        $this->_load();
        return parent::setUpdatedAt($updated_at);
    }

    public function getUpdatedAt()
    {
        $this->_load();
        return parent::getUpdatedAt();
    }

    public function setCreatedAt($created_at)
    {
        $this->_load();
        return parent::setCreatedAt($created_at);
    }

    public function getCreatedAt()
    {
        $this->_load();
        return parent::getCreatedAt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'email', 'mobile', 'password', 'password_salt', 'status', 'updated_at', 'created_at', 'role_id', 'area_id', 'apt_id', 'loginTime', 'logoutTime', 'storeIp');
    }
}