<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityCustomerProxy extends \Entity\Customer implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function updateTrigger($obj)
    {
        $this->_load();
        return parent::updateTrigger($obj);
    }

    public function getOrderFrequence()
    {
        $this->_load();
        return parent::getOrderFrequence();
    }

    public function setLongitude($longitude)
    {
        $this->_load();
        return parent::setLongitude($longitude);
    }

    public function getLongitude()
    {
        $this->_load();
        return parent::getLongitude();
    }

    public function setLattitude($lattitude)
    {
        $this->_load();
        return parent::setLattitude($lattitude);
    }

    public function getLattitude()
    {
        $this->_load();
        return parent::getLattitude();
    }

    public function setDiscountPercent($discountPercent)
    {
        $this->_load();
        return parent::setDiscountPercent($discountPercent);
    }

    public function getDiscountPercent()
    {
        $this->_load();
        return parent::getDiscountPercent();
    }

    public function setDiscountExpiry($discountExpiry)
    {
        $this->_load();
        return parent::setDiscountExpiry($discountExpiry);
    }

    public function getDiscountExpiry()
    {
        $this->_load();
        return parent::getDiscountExpiry();
    }

    public function setVendorId($vendorId)
    {
        $this->_load();
        return parent::setVendorId($vendorId);
    }

    public function getVendorId()
    {
        $this->_load();
        return parent::getVendorId();
    }

    public function setMinOrderValue($minOrderValue)
    {
        $this->_load();
        return parent::setMinOrderValue($minOrderValue);
    }

    public function getMinOrderValue()
    {
        $this->_load();
        return parent::getMinOrderValue();
    }

    public function setMaxOrderValue($maxOrderValue)
    {
        $this->_load();
        return parent::setMaxOrderValue($maxOrderValue);
    }

    public function getMaxOrderValue()
    {
        $this->_load();
        return parent::getMaxOrderValue();
    }

    public function getAvgOrderValue()
    {
        $this->_load();
        return parent::getAvgOrderValue();
    }

    public function getTotalOrderValue()
    {
        $this->_load();
        return parent::getTotalOrderValue();
    }

    public function getTotalOrders()
    {
        $this->_load();
        return parent::getTotalOrders();
    }

    public function getDiscountOrderValue()
    {
        $this->_load();
        return parent::getDiscountOrderValue();
    }

    public function getAvgProcessingDelay()
    {
        $this->_load();
        return parent::getAvgProcessingDelay();
    }

    public function getSerivceWiseRevenue()
    {
        $this->_load();
        return parent::getSerivceWiseRevenue();
    }

    public function getSerivceWiseItems()
    {
        $this->_load();
        return parent::getSerivceWiseItems();
    }

    public function setIsProblematic($isProblematic)
    {
        $this->_load();
        return parent::setIsProblematic($isProblematic);
    }

    public function getIsProblematic()
    {
        $this->_load();
        return parent::getIsProblematic();
    }

    public function setIsStarch($isStarch)
    {
        $this->_load();
        return parent::setIsStarch($isStarch);
    }

    public function getIsStarch()
    {
        $this->_load();
        return parent::getIsStarch();
    }

    public function setIsPerfume($isPerfume)
    {
        $this->_load();
        return parent::setIsPerfume($isPerfume);
    }

    public function getIsPerfume()
    {
        $this->_load();
        return parent::getIsPerfume();
    }

    public function setAgentId(\Entity\PickupBoy $agent_id)
    {
        $this->_load();
        return parent::setAgentId($agent_id);
    }

    public function getAgentId()
    {
        $this->_load();
        return parent::getAgentId();
    }

    public function setPackageId(\Entity\Package $package_id)
    {
        $this->_load();
        return parent::setPackageId($package_id);
    }

    public function getPackageId()
    {
        $this->_load();
        return parent::getPackageId();
    }

    public function setPackageDetails($packageDetails)
    {
        $this->_load();
        return parent::setPackageDetails($packageDetails);
    }

    public function getPackageDetails()
    {
        $this->_load();
        return parent::getPackageDetails();
    }

    public function setPackageUsedDetails($packageUsedDetails)
    {
        $this->_load();
        return parent::setPackageUsedDetails($packageUsedDetails);
    }

    public function getPackageUsedDetails()
    {
        $this->_load();
        return parent::getPackageUsedDetails();
    }

    public function setPackage($package)
    {
        $this->_load();
        return parent::setPackage($package);
    }

    public function getPackage()
    {
        $this->_load();
        return parent::getPackage();
    }

    public function setPackageCode($packageCode)
    {
        $this->_load();
        return parent::setPackageCode($packageCode);
    }

    public function getPackageCode()
    {
        $this->_load();
        return parent::getPackageCode();
    }

    public function setPackageStatus($packageStatus)
    {
        $this->_load();
        return parent::setPackageStatus($packageStatus);
    }

    public function getPackageStatus()
    {
        $this->_load();
        return parent::getPackageStatus();
    }

    public function setOsPlayerId($os_player_id)
    {
        $this->_load();
        return parent::setOsPlayerId($os_player_id);
    }

    public function getOsPlayerId()
    {
        $this->_load();
        return parent::getOsPlayerId();
    }

    public function setOsPushToken($os_push_token)
    {
        $this->_load();
        return parent::setOsPushToken($os_push_token);
    }

    public function getOsPushToken()
    {
        $this->_load();
        return parent::getOsPushToken();
    }

    public function setOwnerId(\Entity\Customer $owner_id = NULL)
    {
        $this->_load();
        return parent::setOwnerId($owner_id);
    }

    public function getOwnerId()
    {
        $this->_load();
        return parent::getOwnerId();
    }

    public function setApartmentId(\Entity\Apartment $apt_id = NULL)
    {
        $this->_load();
        return parent::setApartmentId($apt_id);
    }

    public function getApartmentId()
    {
        $this->_load();
        return parent::getApartmentId();
    }

    public function setBlockId(\Entity\Block $block_id = NULL)
    {
        $this->_load();
        return parent::setBlockId($block_id);
    }

    public function getBlockId()
    {
        $this->_load();
        return parent::getBlockId();
    }

    public function setFlatId(\Entity\Flat $flat_id = NULL)
    {
        $this->_load();
        return parent::setFlatId($flat_id);
    }

    public function getFlatId()
    {
        $this->_load();
        return parent::getFlatId();
    }

    public function setAreaId(\Entity\Area $area_id = NULL)
    {
        $this->_load();
        return parent::setAreaId($area_id);
    }

    public function getAreaId()
    {
        $this->_load();
        return parent::getAreaId();
    }

    public function setCustomerAddress(\Entity\CustomerAddress $customerAddres)
    {
        $this->_load();
        return parent::setCustomerAddress($customerAddres);
    }

    public function getCustomerAddress()
    {
        $this->_load();
        return parent::getCustomerAddress();
    }

    public function getLastAddress()
    {
        $this->_load();
        return parent::getLastAddress();
    }

    public function setPlaceOrder(\Entity\PlaceOrder $placeOrder)
    {
        $this->_load();
        return parent::setPlaceOrder($placeOrder);
    }

    public function getPlaceOrders()
    {
        $this->_load();
        return parent::getPlaceOrders();
    }

    public function getPlaceOrderIds()
    {
        $this->_load();
        return parent::getPlaceOrderIds();
    }

    public function addTransaction(\Entity\TransactionHistory $th)
    {
        $this->_load();
        return parent::addTransaction($th);
    }

    public function getTransactions()
    {
        $this->_load();
        return parent::getTransactions();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setFirstName($firstname)
    {
        $this->_load();
        return parent::setFirstName($firstname);
    }

    public function getFirstName()
    {
        $this->_load();
        return parent::getFirstName();
    }

    public function setLastName($lastname)
    {
        $this->_load();
        return parent::setLastName($lastname);
    }

    public function getLastName()
    {
        $this->_load();
        return parent::getLastName();
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setGender($gender)
    {
        $this->_load();
        return parent::setGender($gender);
    }

    public function getGender()
    {
        $this->_load();
        return parent::getGender();
    }

    public function setFacebook($facebook)
    {
        $this->_load();
        return parent::setFacebook($facebook);
    }

    public function getFacebook()
    {
        $this->_load();
        return parent::getFacebook();
    }

    public function setWallet($wallet)
    {
        $this->_load();
        return parent::setWallet($wallet);
    }

    public function addWallet($wallet)
    {
        $this->_load();
        return parent::addWallet($wallet);
    }

    public function getWallet()
    {
        $this->_load();
        return parent::getWallet();
    }

    public function getBalanceAmount()
    {
        $this->_load();
        return parent::getBalanceAmount();
    }

    public function setRefundAmount($refundAmount)
    {
        $this->_load();
        return parent::setRefundAmount($refundAmount);
    }

    public function getRefundAmount()
    {
        $this->_load();
        return parent::getRefundAmount();
    }

    public function setEmail($email)
    {
        $this->_load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->_load();
        return parent::getEmail();
    }

    public function setDob($dob)
    {
        $this->_load();
        return parent::setDob($dob);
    }

    public function getDob()
    {
        $this->_load();
        return parent::getDob();
    }

    public function setAniversaryDate($aniversaryDate)
    {
        $this->_load();
        return parent::setAniversaryDate($aniversaryDate);
    }

    public function getAniversaryDate()
    {
        $this->_load();
        return parent::getAniversaryDate();
    }

    public function setWhatsapp($whatsapp)
    {
        $this->_load();
        return parent::setWhatsapp($whatsapp);
    }

    public function getWhatsapp()
    {
        $this->_load();
        return parent::getWhatsapp();
    }

    public function setOwnerMobile($ownerMobile)
    {
        $this->_load();
        return parent::setOwnerMobile($ownerMobile);
    }

    public function getOwnerMobile()
    {
        $this->_load();
        return parent::getOwnerMobile();
    }

    public function setOwnerAddress($ownerAddress)
    {
        $this->_load();
        return parent::setOwnerAddress($ownerAddress);
    }

    public function getOwnerAddress()
    {
        $this->_load();
        return parent::getOwnerAddress();
    }

    public function setShowInTele($showInTele)
    {
        $this->_load();
        return parent::setShowInTele($showInTele);
    }

    public function getShowInTele()
    {
        $this->_load();
        return parent::getShowInTele();
    }

    public function setStaying($isStaying)
    {
        $this->_load();
        return parent::setStaying($isStaying);
    }

    public function getStaying()
    {
        $this->_load();
        return parent::getStaying();
    }

    public function setSubType($subType)
    {
        $this->_load();
        return parent::setSubType($subType);
    }

    public function getSubType()
    {
        $this->_load();
        return parent::getSubType();
    }

    public function setUserType($type)
    {
        $this->_load();
        return parent::setUserType($type);
    }

    public function getUserType()
    {
        $this->_load();
        return parent::getUserType();
    }

    public function setAddress($address)
    {
        $this->_load();
        return parent::setAddress($address);
    }

    public function getAddress()
    {
        $this->_load();
        return parent::getAddress();
    }

    public function setRefId($ref_id)
    {
        $this->_load();
        return parent::setRefId($ref_id);
    }

    public function getRefId()
    {
        $this->_load();
        return parent::getRefId();
    }

    public function setOauthId($oauth_id)
    {
        $this->_load();
        return parent::setOauthId($oauth_id);
    }

    public function getOauthId()
    {
        $this->_load();
        return parent::getOauthId();
    }

    public function setPhoneNo($mobile)
    {
        $this->_load();
        return parent::setPhoneNo($mobile);
    }

    public function getPhoneNo()
    {
        $this->_load();
        return parent::getPhoneNo();
    }

    public function getMobile()
    {
        $this->_load();
        return parent::getMobile();
    }

    public function setPassword($password)
    {
        $this->_load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->_load();
        return parent::getPassword();
    }

    public function setRpoints($rpoints)
    {
        $this->_load();
        return parent::setRpoints($rpoints);
    }

    public function addRpoints($rpoints)
    {
        $this->_load();
        return parent::addRpoints($rpoints);
    }

    public function getRpoints()
    {
        $this->_load();
        return parent::getRpoints();
    }

    public function setFirstOrder($firstOrder)
    {
        $this->_load();
        return parent::setFirstOrder($firstOrder);
    }

    public function getFirstOrder()
    {
        $this->_load();
        return parent::getFirstOrder();
    }

    public function setResetPassword($resetPassword)
    {
        $this->_load();
        return parent::setResetPassword($resetPassword);
    }

    public function getResetPassword()
    {
        $this->_load();
        return parent::getResetPassword();
    }

    public function setStatus($status)
    {
        $this->_load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->_load();
        return parent::getStatus();
    }

    public function setUpdatedAt($updated_at)
    {
        $this->_load();
        return parent::setUpdatedAt($updated_at);
    }

    public function getUpdatedAt()
    {
        $this->_load();
        return parent::getUpdatedAt();
    }

    public function setCreatedAt($created_at)
    {
        $this->_load();
        return parent::setCreatedAt($created_at);
    }

    public function getCreatedAt()
    {
        $this->_load();
        return parent::getCreatedAt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'firstname', 'lastname', 'gender', 'email', 'mobile', 'whatsapp', 'type', 'subType', 'password', 'passwordSalt', 'address', 'ownerName', 'ownerMobile', 'ownerAddress', 'ref_id', 'facebook', 'wallet', 'refundAmount', 'oauth_id', 'os_player_id', 'os_push_token', 'rpoints', 'firstOrder', 'resetPassword', 'showInTele', 'isStaying', 'isStarch', 'isProblematic', 'isPerfume', 'minOrderValue', 'maxOrderValue', 'avgOrderValue', 'totalOrderValue', 'discountOrderValue', 'totalOrders', 'serviceWiseRevenue', 'serviceWiseItems', 'lattitude', 'longitude', 'damageAmountTill', 'referralAmountTill', 'avarageProcessingDelay', 'status', 'dob', 'aniversaryDate', 'updated_at', 'created_at', 'apt_id', 'block_id', 'flat_id', 'owner_id', 'area_id', 'placeOrders', 'tempOrders', 'placeOrderIds', 'customerAddress', 'transactionHistory', 'agent_id', 'package_id', 'package', 'packageDetails', 'packageUsedDetails', 'packageCode', 'packageStatus', 'discountPercent', 'discountExpiry', 'vendorId');
    }
}