<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityServiceProxy extends \Entity\Service implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function addAddon(\Entity\Addon $serviceAddon)
    {
        $this->_load();
        return parent::addAddon($serviceAddon);
    }

    public function removeAddon()
    {
        $this->_load();
        return parent::removeAddon();
    }

    public function getAddons()
    {
        $this->_load();
        return parent::getAddons();
    }

    public function getStatusAddons()
    {
        $this->_load();
        return parent::getStatusAddons();
    }

    public function addItem(\Entity\Item $serviceItem)
    {
        $this->_load();
        return parent::addItem($serviceItem);
    }

    public function getItem()
    {
        $this->_load();
        return parent::getItem();
    }

    public function getItemTypeItems($itid)
    {
        $this->_load();
        return parent::getItemTypeItems($itid);
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setCode($code)
    {
        $this->_load();
        return parent::setCode($code);
    }

    public function getCode()
    {
        $this->_load();
        return parent::getCode();
    }

    public function setImage($image)
    {
        $this->_load();
        return parent::setImage($image);
    }

    public function getImage()
    {
        $this->_load();
        return parent::getImage();
    }

    public function setDescription($description)
    {
        $this->_load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->_load();
        return parent::getDescription();
    }

    public function setCost($cost)
    {
        $this->_load();
        return parent::setCost($cost);
    }

    public function getCost()
    {
        $this->_load();
        return parent::getCost();
    }

    public function setDiscount($discount)
    {
        $this->_load();
        return parent::setDiscount($discount);
    }

    public function getDiscount()
    {
        $this->_load();
        return parent::getDiscount();
    }

    public function setStatus($status)
    {
        $this->_load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->_load();
        return parent::getStatus();
    }

    public function setCreatedAt($created_at)
    {
        $this->_load();
        return parent::setCreatedAt($created_at);
    }

    public function getCreatedAt()
    {
        $this->_load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updated_at)
    {
        $this->_load();
        return parent::setUpdatedAt($updated_at);
    }

    public function getUpdatedAt()
    {
        $this->_load();
        return parent::getUpdatedAt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'code', 'image', 'description', 'cost', 'discount', 'status', 'updated_at', 'created_at', 'serviceAddons', 'serviceItems', 'catalogPrices');
    }
}