<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityFlatProxy extends \Entity\Flat implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setVehicle(\Entity\Vehicle $vachile)
    {
        $this->_load();
        return parent::setVehicle($vachile);
    }

    public function getVehicles()
    {
        $this->_load();
        return parent::getVehicles();
    }

    public function setBlockId(\Entity\Block $block_id = NULL)
    {
        $this->_load();
        return parent::setBlockId($block_id);
    }

    public function getBlockId()
    {
        $this->_load();
        return parent::getBlockId();
    }

    public function getHeadOrOwner()
    {
        $this->_load();
        return parent::getHeadOrOwner();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setBhk($bhk)
    {
        $this->_load();
        return parent::setBhk($bhk);
    }

    public function getBhk()
    {
        $this->_load();
        return parent::getBhk();
    }

    public function setIntercom($intercom)
    {
        $this->_load();
        return parent::setIntercom($intercom);
    }

    public function getIntercom()
    {
        $this->_load();
        return parent::getIntercom();
    }

    public function setEusn($eusn)
    {
        $this->_load();
        return parent::setEusn($eusn);
    }

    public function getEusn()
    {
        $this->_load();
        return parent::getEusn();
    }

    public function setSize($size)
    {
        $this->_load();
        return parent::setSize($size);
    }

    public function getSize()
    {
        $this->_load();
        return parent::getSize();
    }

    public function setFacing($facing)
    {
        $this->_load();
        return parent::setFacing($facing);
    }

    public function getFacing()
    {
        $this->_load();
        return parent::getFacing();
    }

    public function setSale($readyToSale)
    {
        $this->_load();
        return parent::setSale($readyToSale);
    }

    public function getSale()
    {
        $this->_load();
        return parent::getSale();
    }

    public function setSalePrice($salePrice)
    {
        $this->_load();
        return parent::setSalePrice($salePrice);
    }

    public function getSalePrice()
    {
        $this->_load();
        return parent::getSalePrice();
    }

    public function setRentPrice($rentPrice)
    {
        $this->_load();
        return parent::setRentPrice($rentPrice);
    }

    public function getRentPrice()
    {
        $this->_load();
        return parent::getRentPrice();
    }

    public function setNofPplStay($nofpplStay)
    {
        $this->_load();
        return parent::setNofPplStay($nofpplStay);
    }

    public function getNofPplStay()
    {
        $this->_load();
        return parent::getNofPplStay();
    }

    public function setCntOneName($cntOneName)
    {
        $this->_load();
        return parent::setCntOneName($cntOneName);
    }

    public function getCntOneName()
    {
        $this->_load();
        return parent::getCntOneName();
    }

    public function setCntOneMobile($cntOneMobile)
    {
        $this->_load();
        return parent::setCntOneMobile($cntOneMobile);
    }

    public function getCntOneMobile()
    {
        $this->_load();
        return parent::getCntOneMobile();
    }

    public function setCntTwoName($cntTwoName)
    {
        $this->_load();
        return parent::setCntTwoName($cntTwoName);
    }

    public function getCntTwoName()
    {
        $this->_load();
        return parent::getCntTwoName();
    }

    public function setCntTwoMobile($cntTwoMobile)
    {
        $this->_load();
        return parent::setCntTwoMobile($cntTwoMobile);
    }

    public function getCntTwoMobile()
    {
        $this->_load();
        return parent::getCntTwoMobile();
    }

    public function setRoccupy($readyToOccupy)
    {
        $this->_load();
        return parent::setRoccupy($readyToOccupy);
    }

    public function getRoccupy()
    {
        $this->_load();
        return parent::getRoccupy();
    }

    public function setStatus($status)
    {
        $this->_load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->_load();
        return parent::getStatus();
    }

    public function setCreatedAt($created_at)
    {
        $this->_load();
        return parent::setCreatedAt($created_at);
    }

    public function getCreatedAt()
    {
        $this->_load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updated_at)
    {
        $this->_load();
        return parent::setUpdatedAt($updated_at);
    }

    public function getUpdatedAt()
    {
        $this->_load();
        return parent::getUpdatedAt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'intercom', 'eusn', 'bhk', 'size', 'facing', 'readyToSale', 'readyToOccupy', 'salePrice', 'rentPrice', 'nofpplStay', 'cntOneName', 'cntOneMobile', 'cntTwoName', 'cntTwoMobile', 'status', 'updated_at', 'created_at', 'block_id', 'customer', 'vehicles', 'adminNotifications');
    }
}