<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityCUnitProxy extends \Entity\CUnit implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setCityId(\Entity\City $city_id = NULL)
    {
        $this->_load();
        return parent::setCityId($city_id);
    }

    public function getCityId()
    {
        $this->_load();
        return parent::getCityId();
    }

    public function setCUDOrder(\Entity\CUDOrder $cudOrder)
    {
        $this->_load();
        return parent::setCUDOrder($cudOrder);
    }

    public function getCUDOrders()
    {
        $this->_load();
        return parent::getCUDOrders();
    }

    public function setCUSOrder(\Entity\CUSOrder $cusOrder)
    {
        $this->_load();
        return parent::setCUSOrder($cusOrder);
    }

    public function getCUSOrders()
    {
        $this->_load();
        return parent::getCUSOrders();
    }

    public function setCUOrderDetails(\Entity\CUOrderDetails $cuOrderDetail)
    {
        $this->_load();
        return parent::setCUOrderDetails($cuOrderDetail);
    }

    public function getCUOrderDetails()
    {
        $this->_load();
        return parent::getCUOrderDetails();
    }

    public function setEmployeeId(\Entity\Employee $emp_id)
    {
        $this->_load();
        return parent::setEmployeeId($emp_id);
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setCode($code)
    {
        $this->_load();
        return parent::setCode($code);
    }

    public function getCode()
    {
        $this->_load();
        return parent::getCode();
    }

    public function setAddress($address)
    {
        $this->_load();
        return parent::setAddress($address);
    }

    public function getAddress()
    {
        $this->_load();
        return parent::getAddress();
    }

    public function setStatus($status)
    {
        $this->_load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->_load();
        return parent::getStatus();
    }

    public function setCreatedAt($created_at)
    {
        $this->_load();
        return parent::setCreatedAt($created_at);
    }

    public function getCreatedAt()
    {
        $this->_load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updated_at)
    {
        $this->_load();
        return parent::setUpdatedAt($updated_at);
    }

    public function getUpdatedAt()
    {
        $this->_load();
        return parent::getUpdatedAt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'code', 'address', 'status', 'cusOrders', 'cudOrders', 'CUEmployees', 'cuOrderDetails', 'city_id', 'updated_at', 'created_at');
    }
}