<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityApartmentProxy extends \Entity\Apartment implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setVehicle(\Entity\Vehicle $vachile)
    {
        $this->_load();
        return parent::setVehicle($vachile);
    }

    public function getVehicles()
    {
        $this->_load();
        return parent::getVehicles();
    }

    public function setBlock(\Entity\Block $block)
    {
        $this->_load();
        return parent::setBlock($block);
    }

    public function getBlocks()
    {
        $this->_load();
        return parent::getBlocks();
    }

    public function getCustomers()
    {
        $this->_load();
        return parent::getCustomers();
    }

    public function setAreaId(\Entity\Area $area_id = NULL)
    {
        $this->_load();
        return parent::setAreaId($area_id);
    }

    public function getAreaId()
    {
        $this->_load();
        return parent::getAreaId();
    }

    public function setCatalogId(\Entity\Catalog $catalog_id)
    {
        $this->_load();
        return parent::setCatalogId($catalog_id);
    }

    public function getCatalogId()
    {
        $this->_load();
        return parent::getCatalogId();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setCode($code)
    {
        $this->_load();
        return parent::setCode($code);
    }

    public function getCode()
    {
        $this->_load();
        return parent::getCode();
    }

    public function setAddress($address)
    {
        $this->_load();
        return parent::setAddress($address);
    }

    public function getAddress()
    {
        $this->_load();
        return parent::getAddress();
    }

    public function setPincode($pincode)
    {
        $this->_load();
        return parent::setPincode($pincode);
    }

    public function getPincode()
    {
        $this->_load();
        return parent::getPincode();
    }

    public function setMobile($mobile)
    {
        $this->_load();
        return parent::setMobile($mobile);
    }

    public function getMobile()
    {
        $this->_load();
        return parent::getMobile();
    }

    public function setLandmark($landmark)
    {
        $this->_load();
        return parent::setLandmark($landmark);
    }

    public function getLandmark()
    {
        $this->_load();
        return parent::getLandmark();
    }

    public function setStatus($status)
    {
        $this->_load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->_load();
        return parent::getStatus();
    }

    public function setCreatedAt($created_at)
    {
        $this->_load();
        return parent::setCreatedAt($created_at);
    }

    public function getCreatedAt()
    {
        $this->_load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updated_at)
    {
        $this->_load();
        return parent::setUpdatedAt($updated_at);
    }

    public function getUpdatedAt()
    {
        $this->_load();
        return parent::getUpdatedAt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'code', 'address', 'pincode', 'landmark', 'mobile', 'status', 'area_id', 'catalog_id', 'customers', 'blocks', 'vachiles');
    }
}