<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityPickupBoyProxy extends \Entity\PickupBoy implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getPackageCustomers()
    {
        $this->_load();
        return parent::getPackageCustomers();
    }

    public function setAreaId(\Entity\Area $area_id = NULL)
    {
        $this->_load();
        return parent::setAreaId($area_id);
    }

    public function getAreaId()
    {
        $this->_load();
        return parent::getAreaId();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setEmail($email)
    {
        $this->_load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->_load();
        return parent::getEmail();
    }

    public function setImage($image)
    {
        $this->_load();
        return parent::setImage($image);
    }

    public function getImage()
    {
        $this->_load();
        return parent::getImage();
    }

    public function setMobile($mobile)
    {
        $this->_load();
        return parent::setMobile($mobile);
    }

    public function getMobile()
    {
        $this->_load();
        return parent::getMobile();
    }

    public function setPassword($password)
    {
        $this->_load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->_load();
        return parent::getPassword();
    }

    public function setToken($token)
    {
        $this->_load();
        return parent::setToken($token);
    }

    public function getToken()
    {
        $this->_load();
        return parent::getToken();
    }

    public function setStatus($status)
    {
        $this->_load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->_load();
        return parent::getStatus();
    }

    public function setUpdatedAt($updated_at)
    {
        $this->_load();
        return parent::setUpdatedAt($updated_at);
    }

    public function getUpdatedAt()
    {
        $this->_load();
        return parent::getUpdatedAt();
    }

    public function setCreatedAt($created_at)
    {
        $this->_load();
        return parent::setCreatedAt($created_at);
    }

    public function getCreatedAt()
    {
        $this->_load();
        return parent::getCreatedAt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'email', 'image', 'mobile', 'password', 'passwordSalt', 'token', 'status', 'updated_at', 'created_at', 'area_id', 'customers');
    }
}