<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityCustomerAddressProxy extends \Entity\CustomerAddress implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setCustomerId(\Entity\Customer $cust_id = NULL)
    {
        $this->_load();
        return parent::setCustomerId($cust_id);
    }

    public function getCustomerId()
    {
        $this->_load();
        return parent::getCustomerId();
    }

    public function setAreaId(\Entity\Area $area_id = NULL)
    {
        $this->_load();
        return parent::setAreaId($area_id);
    }

    public function getAreaId()
    {
        $this->_load();
        return parent::getAreaId();
    }

    public function getStoreId()
    {
        $this->_load();
        return parent::getStoreId();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setAddress($address)
    {
        $this->_load();
        return parent::setAddress($address);
    }

    public function getAddress()
    {
        $this->_load();
        return parent::getAddress();
    }

    public function setLandmark($landmark)
    {
        $this->_load();
        return parent::setLandmark($landmark);
    }

    public function getLandmark()
    {
        $this->_load();
        return parent::getLandmark();
    }

    public function setPincode($pincode)
    {
        $this->_load();
        return parent::setPincode($pincode);
    }

    public function getPincode()
    {
        $this->_load();
        return parent::getPincode();
    }

    public function setStatus($status)
    {
        $this->_load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->_load();
        return parent::getStatus();
    }

    public function setUpdatedAt($updated_at)
    {
        $this->_load();
        return parent::setUpdatedAt($updated_at);
    }

    public function getUpdatedAt()
    {
        $this->_load();
        return parent::getUpdatedAt();
    }

    public function setCreatedAt($created_at)
    {
        $this->_load();
        return parent::setCreatedAt($created_at);
    }

    public function getCreatedAt()
    {
        $this->_load();
        return parent::getCreatedAt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'address', 'landmark', 'pincode', 'status', 'updated_at', 'created_at', 'area_id', 'cust_id', 'placeOrderIds');
    }
}